拍卖系统/src/拍卖系统/Models/Member.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace 拍卖系统.Models
{
	/// <summary>
	/// 会员
	/// </summary>
	public class Member : EntityBase<int>
	{
		/// <summary>
		/// 用户组ID
		/// </summary>
		public int GroupId { get; set; }
		/// <summary>
		/// 会员等级ID
		/// </summary>
		public int LevelId { get; set; }
		/// <summary>
		/// 推荐人ID
		/// </summary>
		public int AgentId { get; set; }
		/// <summary>
		/// 微信openid
		/// </summary>
		public string OpenId { get; set; }
		/// <summary>
		/// 手机
		/// </summary>
		public string Mobile { get; set; }
		/// <summary>
		/// 密码
		/// </summary>
		public string Password { get; set; }
		/// <summary>
		/// 微信号
		/// </summary>
		public string Weixin { get; set; }
		/// <summary>
		/// 累计佣金
		/// </summary>
		public decimal Commission { get; set; }
		/// <summary>
		/// 打款佣金
		/// </summary>
		public decimal Commission_Pay { get; set; }
		/// <summary>
		/// 备注
		/// </summary>
		public string Content { get; set; }
		/// <summary>
		/// 成为代理时间
		/// </summary>
		public DateTime AgentTime { get; set; } = DateTime.Now;
		/// <summary>
		/// 状态
		/// </summary>
		public bool Status { get; set; } = true;
		/// <summary>
		/// 是否代理
		/// </summary>
		public bool IsAgent { get; set; } = false;
		/// <summary>
		/// 点击数
		/// </summary>
		public int ClickCount { get; set; }
		/// <summary>
		/// 分销商等级ID
		/// </summary>
		public int AgentLevelId { get; set; }
		public string NoticeSet { get; set; }
		/// <summary>
		/// 昵称
		/// </summary>
		public string NickName { get; set; }
		/// <summary>
		/// 积分1（整形）
		/// </summary>
		public int Credit1 { get; set; }
		/// <summary>
		/// 积分2（可小数）
		/// </summary>
		public decimal Credit2 { get; set; }
		/// <summary>
		/// 生日
		/// </summary>
		public DateTime Birthday { get; set; } = DateTime.Now;
		/// <summary>
		/// 性别
		/// </summary>
		public Gender Gender { get; set; } = Gender.未知;
		/// <summary>
		/// 头像
		/// </summary>
		public string Avatar { get; set; }
		/// <summary>
		/// 省
		/// </summary>
		public string Province { get; set; }
		/// <summary>
		/// 市
		/// </summary>
		public string City { get; set; }
		/// <summary>
		/// 区
		/// </summary>
		public string Area { get; set; }
	}
	public enum Gender
	{
		未知,
		男,
		女
	}
}

拍卖系统/src/拍卖系统/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using 拍卖系统.Data;
using 拍卖系统.Controllers.Attributes;
using Microsoft.EntityFrameworkCore;

namespace 拍卖系统.Controllers
{
	public class AuctionController : ControllerBase
	{
		public AuctionController(ApplicationDbContext context) : base(context) { }
		[WeixinAuth]
		public async Task<IActionResult> Index(int id)
		{
			var member = await db.Members.SingleOrDefaultAsync(m => m.OpenId == OAuth.openid);
			if (member == null)
				return RedirectToAction("BindMemberCard", "Weixin");

			ViewData["Mid"] = member.Id;

			var auction = await db.Auctions.Include(a => a.Good).SingleOrDefaultAsync(a => a.Id == id);
			if (auction == null)
				return NotFound();

			return View(auction);
		}
	}
}

拍卖系统/src/拍卖系统/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using 拍卖系统.Data;
using 拍卖系统.Controllers.Attributes;
using Microsoft.EntityFrameworkCore;

namespace 拍卖系统.Controllers
{
	public class MemberController : ControllerBase
	{
		public MemberController(ApplicationDbContext context) : base(context) { }
		[WeixinAuth]
		public async Task<IActionResult> Index()
		{
			var member = await db.Members.SingleOrDefaultAsync(m => m.OpenId == OAuth.openid);

			//拍卖列表
			ViewData["List"] = db.Auctions.Include(a => a.Good).OrderByDescending(a => a.Id).Take(6);

			return View(member);
		}
	}
}

拍卖系统/src/拍卖系统/Views/Member/Index.cshtml
@model Member
@{
	IEnumerable<Auction> list = ViewData["List"] as IEnumerable<Auction>;
}
<h2>会员中心</h2>
<div class="weui_panel_bd">
	<div class="weui_media_box weui_media_appmsg">
		<div class="weui_media_hd">
			<img class="weui_media_appmsg_thumb" src="@Model.Avatar" alt="">
		</div>
		<div class="weui_media_bd">
			<h4 class="weui_media_title">@Model.NickName</h4>
			<p class="weui_media_desc">欢迎回来</p>
		</div>
	</div>
</div>
<div class="row">
	@foreach (var a in list)
	{
		<div class="col-xs-6 col-sm-6 col-md-4">
			<div class="thumbnail">
				<a asp-controller="Auction" asp-action="Index" asp-route-id="@a.Id"><img src="@a.Good.Picture" alt="@a.Name"></a>
				<div class="caption">
					<h3>@a.Name</h3><small>起拍价：￥@a.Onset</small>
					<p>@a.Good.Description</p>
					<p><a asp-controller="Auction" asp-action="Index" asp-route-id="@a.Id" class="btn btn-primary" role="button">参与拍卖</a></p>
				</div>
			</div>
		</div>
	}
</div>