拍卖系统/src/拍卖系统/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using 拍卖系统.Data;
using 拍卖系统.Controllers.Attributes;
using Microsoft.EntityFrameworkCore;

namespace 拍卖系统.Controllers
{
	public class MemberController : ControllerBase
	{
		public MemberController(ApplicationDbContext context) : base(context) { }
		[WeixinAuth]
		public async Task<IActionResult> Index()
		{
			var member = await db.Members.SingleOrDefaultAsync(m => m.OpenId == OAuth.openid);

			//拍卖列表
			ViewData["List"] = db.Auctions.Include(a => a.Good).OrderByDescending(a => a.Id).Take(6);

			return View(member);
		}
	}
}

拍卖系统/src/拍卖系统/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="lswapp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 拍卖系统</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/lib/weui/dist/style/weui.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/lib/weui/dist/style/weui.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
	<link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">拍卖系统</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-controller="Member" asp-action="Index">会员中心</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - 拍卖系统</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
    </environment>
	<script src="~/lib/signalr/jquery.signalR.min.js"></script>
	<script src="/signalr/js"></script>
	<script src="~/lib/toastr/toastr.min.js"></script>
	@if (ViewData["CommMessage"] != null)
	{
		<script type="text/javascript">
		toastr.options.positionClass = 'toast-top-center';
		toastr.success('@ViewData["CommMessage"]');
		</script>
	}
	@if (@ViewData["ErrMessage"] != null)
	{
		<script type="text/javascript">
		toastr.options.positionClass = 'toast-top-center';
		toastr.error('@ViewData["ErrMessage"]');
		</script>
	}
    @RenderSection("scripts", required: false)
</body>
</html>